//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api.Infra.Resourses {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Api.Infra.Resourses.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message not implemented..
        /// </summary>
        public static string MSG000000000 {
            get {
                return ResourceManager.GetString("MSG000000000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already exist a country with same name..
        /// </summary>
        public static string MSG000000001 {
            get {
                return ResourceManager.GetString("MSG000000001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already exist a country with same code..
        /// </summary>
        public static string MSG000000002 {
            get {
                return ResourceManager.GetString("MSG000000002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not filled..
        /// </summary>
        public static string MSG000000003 {
            get {
                return ResourceManager.GetString("MSG000000003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name is empty..
        /// </summary>
        public static string MSG000000004 {
            get {
                return ResourceManager.GetString("MSG000000004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code is empty..
        /// </summary>
        public static string MSG000000005 {
            get {
                return ResourceManager.GetString("MSG000000005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code length must be 3 (ALPHA-3)..
        /// </summary>
        public static string MSG000000006 {
            get {
                return ResourceManager.GetString("MSG000000006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid type of person..
        /// </summary>
        public static string MSG000000007 {
            get {
                return ResourceManager.GetString("MSG000000007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country is empty..
        /// </summary>
        public static string MSG000000008 {
            get {
                return ResourceManager.GetString("MSG000000008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This person already is a contractee..
        /// </summary>
        public static string MSG000000009 {
            get {
                return ResourceManager.GetString("MSG000000009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contractee need a person..
        /// </summary>
        public static string MSG000000010 {
            get {
                return ResourceManager.GetString("MSG000000010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country not found..
        /// </summary>
        public static string MSG000000011 {
            get {
                return ResourceManager.GetString("MSG000000011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is required {0} to create a person in the selected country..
        /// </summary>
        public static string MSG000000012 {
            get {
                return ResourceManager.GetString("MSG000000012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} country obligation alreaby been added..
        /// </summary>
        public static string MSG000000013 {
            get {
                return ResourceManager.GetString("MSG000000013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} country obligation do not exists..
        /// </summary>
        public static string MSG000000014 {
            get {
                return ResourceManager.GetString("MSG000000014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must delete contractee before delete person..
        /// </summary>
        public static string MSG000000015 {
            get {
                return ResourceManager.GetString("MSG000000015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already exist a service type with same name..
        /// </summary>
        public static string MSG000000016 {
            get {
                return ResourceManager.GetString("MSG000000016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract need a service type..
        /// </summary>
        public static string MSG000000017 {
            get {
                return ResourceManager.GetString("MSG000000017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract need a contractee..
        /// </summary>
        public static string MSG000000018 {
            get {
                return ResourceManager.GetString("MSG000000018", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract need a contractor..
        /// </summary>
        public static string MSG000000019 {
            get {
                return ResourceManager.GetString("MSG000000019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid contract status for this stage of contract..
        /// </summary>
        public static string MSG000000020 {
            get {
                return ResourceManager.GetString("MSG000000020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contractor need a person..
        /// </summary>
        public static string MSG000000021 {
            get {
                return ResourceManager.GetString("MSG000000021", resourceCulture);
            }
        }
    }
}
